version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:45"
      timezone: "Europe/Berlin"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:45"
      timezone: "Europe/Berlin"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:45"
      timezone: "Europe/Berlin"
