sonar.projectKey=moureg2001_go-gh-release-test
sonar.organization=moureg2001
sonar.sources=.
sonar.exclusions=**/*_test.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
